---
name: svgen
version: "{{major}}.{{minor}}.{{patch}}"
description: "A tool for working with scalable vector graphics."
entry: {{entry}}
requirements:
  - vcorelib
dev_requirements:
  - setuptools-wrapper
